import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from 'sonner'
import NextUIProviderContext from '@/providers/NextUIProvider'
import { NavBar } from '@/components/Navbar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={inter.className}>
        <ClerkProvider>
          <NextUIProviderContext>
            <Toaster />
            <NavBar />
            {children}
          </NextUIProviderContext>
        </ClerkProvider>
      </body>
    </html>
  )
}
