import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from 'sonner'
import NextUIProviderContext from '@/providers/NextUIProvider'
import { NavBar } from '@/components/Navbar'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: 'Lunchfip',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/favicons/favicon-lunchfip-light.ico',
        href: '/favicons/favicon-lunchfip-light.ico'
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/favicons/favicon-lunchfip-dark.ico',
        href: '/favicons/favicon-lunchfip-dark.ico'
      }
    ]
  }
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${inter.variable} font-sans`}>
        <ClerkProvider>
          <NextUIProviderContext>
            <Toaster />
            <NavBar />
            {children}
          </NextUIProviderContext>
        </ClerkProvider>
      </body>
    </html>
  )
}
