import type { Metadata } from 'next'
import { Aside } from '@/components/Aside'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function EmployeeLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <main>
      <Aside />
      {children}
    </main>
  )
}
